fun main() {
    /*Exception is a runtime error which occurs in the program and leads to program termination
    * They may occur due to running out of memory space,
    * an array being out of bound,
    * dividing a number by zero.
    * Exception handling is a technique that handles the runtime problem and maintains the flow of program execution*/

    /*keywords are
    * Try - Contains set of statements which might generate an exception
    * Catch - catch an error
    * Throw - throw an exception explicitly
    * Finally - Executes whether exception is handled or not*/

    /* Types of errors:
    * logical
    * syntax
    * runtime*/
}